import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { DefaultHeader, DefaultFooter } from "@/components/global";

const cigra = localFont({
  src: [
    {
      path: "./fonts/Cigra/Cigra.woff",
      weight: "100",
      style: "normal",
    },
  ],
});

const tajawal = localFont({
  src: [
    {
      path: "./fonts/Tajawal/Tajawal-ExtraLight.ttf",
      weight: "100",
      style: "normal",
    },
    {
      path: "./fonts/Tajawal/Tajawal-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Tajawal/Tajawal-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Tajawal/Tajawal-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Tajawal/Tajawal-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Tajawal/Tajawal-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/Tajawal/Tajawal-Black.ttf",
      weight: "900",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Nayyir Scenes",
  description: "Generated by create next app",
  keywords: [],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${tajawal.className} ${cigra.className}`}>
        <DefaultHeader />
        {children}
        <DefaultFooter />
      </body>
    </html>
  );
}
